package form;

import java.sql.*;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.awt.print.PrinterJob;

public class laporan extends javax.swing.JFrame {
    private Connection connection;
    private Statement statement;
    private ResultSet resultSet;

    public laporan() {
        initComponents();
        
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/database_restoran", "root", "");
            statement = connection.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA LAPORAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 776, 230));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 270, 110, -1));

        jButton1.setText("cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 269, -1, -1));

        jButton2.setText("Cetak Laporan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 269, -1, -1));

        jButton3.setText("Tampilkan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 269, -1, -1));

        jButton4.setText("Simpan Laporan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 269, -1, -1));

        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AA1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 810, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kodePelanggan = jTextField3.getText();
        String query = "SELECT dpb.kode_transaksi, dpb.admin, dpb.nama_makanan, dpb.harga, dpb.jumlah, dpb.total, " +
            "dp.kode_pelanggan, dp.nama_pelanggan " +
            "FROM data_pesan_bayar dpb " +
            "JOIN data_pelanggan dp ON dpb.kode_pelanggan = dp.kode_pelanggan " +
            "WHERE dp.kode_pelanggan = '" + kodePelanggan + "'";
        try {
        resultSet = statement.executeQuery(query);
        
        Vector<Vector<Object>> data = new Vector<>();
        while (resultSet.next()) {
            Vector<Object> row = new Vector<>();
            row.add(resultSet.getString("kode_transaksi"));
            row.add(resultSet.getString("admin"));
            row.add(resultSet.getString("nama_makanan"));
            row.add(resultSet.getString("harga"));
            row.add(resultSet.getString("jumlah"));
            row.add(resultSet.getString("total"));
            row.add(resultSet.getString("kode_pelanggan"));
            row.add(resultSet.getString("nama_pelanggan"));
            data.add(row);
        }

        DefaultTableModel tableModel = new DefaultTableModel(
            data,
            new Vector<>(Arrays.asList("Kode Transaksi", "Admin", "Nama Makanan", "Harga", "Jumlah", "Total",
                "Kode Pelanggan", "Nama Pelanggan"))
         );
        jTable1.setModel(tableModel);
    } catch (SQLException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       String query = "SELECT dpb.kode_transaksi, dpb.admin, dpb.nama_makanan, dpb.harga, dpb.jumlah, dpb.total, " +
            "dp.kode_pelanggan, dp.nama_pelanggan " +
            "FROM data_pesan_bayar dpb " +
            "JOIN data_pelanggan dp ON dpb.kode_pelanggan = dp.kode_pelanggan";

    try {
        resultSet = statement.executeQuery(query);

        Vector<Vector<Object>> data = new Vector<>();
        while (resultSet.next()) {
            Vector<Object> row = new Vector<>();
            row.add(resultSet.getString("kode_transaksi"));
            row.add(resultSet.getString("admin"));
            row.add(resultSet.getString("nama_makanan"));
            row.add(resultSet.getString("harga"));
            row.add(resultSet.getString("jumlah"));
            row.add(resultSet.getString("total"));
            row.add(resultSet.getString("kode_pelanggan"));
            row.add(resultSet.getString("nama_pelanggan"));
            data.add(row);
        }

        DefaultTableModel tableModel = new DefaultTableModel(
                data,
                new Vector<>(Arrays.asList("Kode Transaksi", "Admin", "Nama Makanan", "Harga", "Jumlah", "Total",
                        "Kode Pelanggan", "Nama Pelanggan"))
        );

        // Setel model tabel ke JTable di form laporan
        jTable1.setModel(tableModel);
    } catch (SQLException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

      String query = "SELECT dpb.kode_transaksi, dpb.admin, dpb.nama_makanan, dpb.harga, dpb.jumlah, dpb.total, " +
            "dp.kode_pelanggan, dp.nama_pelanggan " +
            "FROM data_pesan_bayar dpb " +
            "JOIN data_pelanggan dp ON dpb.kode_pelanggan = dp.kode_pelanggan";

    PreparedStatement preparedStatement = null;
    PreparedStatement selectStatement = null;
    ResultSet laporanResultSet = null;

    try {
        resultSet = statement.executeQuery(query);

// Hapus semua data dari tabel laporan sebelum menyimpan data baru
statement.executeUpdate("DELETE FROM laporan");

resultSet.close(); // Menutup ResultSet di sini
        
        
        ResultSet resultSet = statement.executeQuery(query);

       

        while (resultSet.next()) {
            String kodeTransaksi = resultSet.getString("kode_transaksi");
            String admin = resultSet.getString("admin");
            String namaMakanan = resultSet.getString("nama_makanan");
            String harga = resultSet.getString("harga");
            String jumlah = resultSet.getString("jumlah");
            String total = resultSet.getString("total");
            String kodePelanggan = resultSet.getString("kode_pelanggan");
            String namaPelanggan = resultSet.getString("nama_pelanggan");

            // Simpan data ke tabel laporan
            String insertQuery = "INSERT INTO laporan (kode_transaksi, admin, nama_makanan, harga, jumlah, total, kode_pelanggan, nama_pelanggan, pesanan, jumlah_pemesanan, total_pemesanan) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            preparedStatement = connection.prepareStatement(insertQuery);
            preparedStatement.setString(1, kodeTransaksi);
            preparedStatement.setString(2, admin);
            preparedStatement.setString(3, namaMakanan);
            preparedStatement.setString(4, harga);
            preparedStatement.setString(5, jumlah);
            preparedStatement.setString(6, total);
            preparedStatement.setString(7, kodePelanggan);
            preparedStatement.setString(8, namaPelanggan);
            preparedStatement.setString(9, namaPelanggan);
            preparedStatement.setString(10, namaPelanggan);
            preparedStatement.setString(11, namaPelanggan);

            preparedStatement.executeUpdate();
        }

        // Tampilkan data di tabel JTable di form laporan
        selectStatement = connection.prepareStatement("SELECT * FROM laporan");
        laporanResultSet = selectStatement.executeQuery();
        Vector<Vector<Object>> data = new Vector<>();
        while (laporanResultSet.next()) {
            Vector<Object> row = new Vector<>();
            row.add(laporanResultSet.getString("kode_transaksi"));
            row.add(laporanResultSet.getString("admin"));
            row.add(laporanResultSet.getString("nama_makanan"));
            row.add(laporanResultSet.getString("harga"));
            row.add(laporanResultSet.getString("jumlah"));
            row.add(laporanResultSet.getString("total"));
            row.add(laporanResultSet.getString("kode_pelanggan"));
            row.add(laporanResultSet.getString("nama_pelanggan"));
            row.add(laporanResultSet.getString("nama_pelanggan"));
            row.add(laporanResultSet.getString("pesanan"));
            row.add(laporanResultSet.getString("jumlah_pemesanan"));
            row.add(laporanResultSet.getString("total_pemesanan"));
            data.add(row);
        }

        DefaultTableModel tableModel = new DefaultTableModel(
                data,
                new Vector<>(Arrays.asList("Kode Transaksi", "Admin", "Nama Makanan", "Harga", "Jumlah", "Total",
                        "Kode Pelanggan", "Nama Pelanggan"))
        );

        jTable1.setModel(tableModel);

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            // Tutup objek PreparedStatement
            if (preparedStatement != null) {
                preparedStatement.close();
            }
            if (selectStatement != null) {
                selectStatement.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           cetakLaporan();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         menuUtama menu = new menuUtama();
          menu.setVisible(true);
          menu.pack();
          menu.setLocationRelativeTo(null);
          menu.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    
    
    private void cetakLaporan() {
    try {
        // Ambil instance dari PrinterJob
        PrinterJob printerJob = PrinterJob.getPrinterJob();

        // Setel kelas yang akan mencetak laporan (kelas ini harus mengimplementasikan Printable interface)
        printerJob.setPrintable(jTable1.getPrintable(
                JTable.PrintMode.FIT_WIDTH, null, null));

        // Tampilkan dialog cetak
        if (printerJob.printDialog()) {
            // Mulai proses pencetakan
            printerJob.print();
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencetak laporan.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
